# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

# default values
setenv load_addr "0x45000000"
setenv overlay_error "false"
setenv verbosity "1"
setenv splashfile "boot.bmp"
setenv splashimage "0x66000000"

# Print boot source
itest.b *0x10028 == 0x00 && echo "U-boot loaded from SD"
itest.b *0x10028 == 0x02 && echo "U-boot loaded from eMMC or secondary SD"
itest.b *0x10028 == 0x03 && echo "U-boot loaded from SPI"

echo "Boot script loaded from ${devtype}"

if test -e ${devtype} ${devnum} ${prefix}armbianEnv.txt; then
	load ${devtype} ${devnum} ${load_addr} ${prefix}armbianEnv.txt
	env import -t ${load_addr} ${filesize}
fi

# Show a splash image from the boot partition, if one is there.
# ${devtype}/${devnum} rather than a fixed device, so this works whether we
# booted from eMMC or USB. The load is guarded: an image without a splash
# file simply skips it rather than failing the boot.
# Disable by setting splashfile= (empty) in armbianEnv.txt.
if test -n "${splashfile}"; then
	if load ${devtype} ${devnum} ${splashimage} ${prefix}${splashfile}; then
		# Nested if so a failure here cannot abort the boot script. An
		# older u-boot on eMMC without CONFIG_CMD_BMP would fail on an
		# unknown command, and that must not stop the board booting.
		if bmp display ${splashimage} m m; then
			echo "Splash displayed"
		fi
	fi
fi

if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=ttyS0,115200 console=tty1"; fi
if test "${console}" = "serial"; then setenv consoleargs "console=ttyS0,115200"; fi

setenv bootargs "${consoleargs} consoleblank=0 loglevel=${verbosity} usb-storage.quirks=${usbstoragequirks} ${extraargs} ${extraboardargs}"

load ${devtype} ${devnum} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
fdt addr ${fdt_addr_r}
fdt resize 65536

if load ${devtype} ${devnum} ${load_addr} ${prefix}dtb/allwinner/overlay/${overlay_prefix}-fixup.scr; then
	echo "Applying kernel provided DT fixup script (${overlay_prefix}-fixup.scr)"
	source ${load_addr}
fi

load ${devtype} ${devnum} ${ramdisk_addr_r} ${prefix}uInitrd
load ${devtype} ${devnum} ${kernel_addr_r} ${prefix}Image

booti ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
