name: Build Armbian
on:
  push:
  workflow_dispatch:

env:
  TERM: xterm-256color

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'intelligent-agent/build'
      path: 'build'
    - uses: actions/checkout@v3
      path: 'Reflash'

    - name: 'Copy files and run build'
      working-directory: ./build
      run: |
      cp Reflash/armbian/reflash.sh build/
      cp Reflash/armbian/customize-image.sh build/userpatches
      sed -i 's/-it //g' build/userpathces/config-docker.conf
      sh ./reflash.sh
