name: Build Armbian
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
env:
  TERM: xterm-256color

jobs:
  package:
    runs-on: self-hosted
    steps:
    - name: Make filename
      run: echo "VERSION=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Use tag if tagged
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - uses: actions/checkout@v3
      with:
        path: 'Reflash'
    - name: Use Node.js '18'
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Run tests
      working-directory: ./Reflash
      run: |
        pip3 install pytest requests-mock
        make tests

    - name: install and build
      working-directory: ./Reflash/client
      run: |
        npm ci
        npm run build

    - name: Make archive with version file
      run: |
        make package
        echo ${VERSION} > zip/reflash/reflash.version
        make tar
        cp reflash.tar.gz ../
      working-directory: ./Reflash
  build:
    needs: package
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'intelligent-agent/build'
        path: 'build'
        clean: false
    - uses: actions/checkout@v3
      with:
        path: 'Reflash'

    - name: 'Copy files'
      run: |
        mkdir -p build/userpatches/overlay
        mkdir -p build/userpatches/kernel/archive/sunxi-5.15
        mkdir -p build/userpatches/u-boot/u-boot-sunxi
        cp reflash.tar.gz build/userpatches/overlay
        cp Reflash/armbian/reflash.sh build/
        cp Reflash/armbian/lib.config build/userpatches
        cp Reflash/armbian/customize-image.sh build/userpatches
        cp Reflash/armbian/config-docker.conf build/userpatches
        cp Reflash/armbian/0001-Add-support-for-Recore-dtbs.patch build/userpatches/kernel/archive/sunxi-5.15
        cp Reflash/armbian/0002-Add-support-for-Recore.patch build/userpatches/u-boot/u-boot-sunxi

    - name: Run build
      working-directory: ./build
      run: sh ./reflash.sh

    - name: Make filename
      run: echo "VERSION=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Use tag if tagged
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Delete all old images
      run: rm -f *.img.xz

    - name: Move and rename file
      run: cp build/output/images/Armbian_23.02.0-trunk_Recore_bullseye_current_5.15.93_minimal.img.xz ./Reflash-${VERSION}.img.xz

    - name: Release if tagged
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        allowUpdates: true
        artifacts: Reflash-v*.img.xz
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
