name: Build Armbian
on:
  push:
  workflow_dispatch:

env:
  TERM: xterm-256color

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'intelligent-agent/build'
        path: 'build'
    - uses: actions/checkout@v3
      with:
        path: 'Reflash'

    - name: 'Copy files'
      run: |
        cp Reflash/armbian/reflash.sh build/
        cp Reflash/armbian/customize-image.sh build/userpatches
        cp Reflash/armbian/config-docker.conf build/userpatches

    - name: Run build
      working-directory: ./build
      run: sh ./reflash.sh
