name: Build Armbian
on:
  push:
  workflow_dispatch:

env:
  TERM: xterm-256color

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'intelligent-agent/build'
    - run: |
      cp config-docker-gh.conf userpatches
      ./compile.sh docker config-docker-gh.conf \
        BOARD=recore \
        BRANCH=current \
        RELEASE=bullseye \
        BUILD_MINIMAL=yes \
        BUILD_DESKTOP=no \
        KERNEL_ONLY=no \
        KERNEL_CONFIGURE=no \
        WIREGUARD=no \
        BOOTSIZE=256 \
        BOOTFS_TYPE="ext4" \
        CLEAN_LEVEL="" \
        COMPRESS_OUTPUTIMAGE=sha,gpg,xz
