# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js '18'
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm run build
    - name: Make archive
      run: make gzip
      working-directory: ./
    - uses: actions/upload-artifact@v3
      working-directory: ./zip
      with:
        name: reflash
        path: reflash
