name: Package Application
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js '18'
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm run build
    - name: Make archive
      run: make package
      working-directory: ./
    - uses: actions/upload-artifact@v3
      with:
        name: reflash
        path: zip
